LEXC        = flex
LEX_SRC     = scanner.l
LEX_OUTPUT  = lex.yy.c
CC          = gcc
TARGET      = scanner
CFLAGS      = -lfl

.PHONY: all clean

all: ${TARGET}

${TARGET}: ${LEX_OUTPUT}
	${CC} -o $@ $^ ${CFLAGS}

${LEX_OUTPUT}: ${LEX_SRC}
	${LEXC} -o $@ $^

clean: 
	rm -rf ${LEX_OUTPUT} ${TARGET}
